defmodule FinanceSmith.Repo.Migrations.AddCreditLimit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts, prefix: "core") do
      add(:credit_limit, :bigint)
    end
  end

  def down do
    alter table(:accounts, prefix: "core") do
      remove(:credit_limit)
    end
  end
end
