defmodule FinanceSmith.Repo.Migrations.AddTransactionIndexesAndIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:transactions, [:account_id, :personal_finance_category],
             name: "transactions_outflow_by_account_category_index",
             where: "amount > 0",
             prefix: "core"
           )

    create index(:transactions, [:account_id, :personal_finance_category],
             name: "transactions_account_id_category_index",
             prefix: "core"
           )

    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id, :date],
        name: "transactions_unique_plaid_transaction_id_index",
        prefix: "core"
      )
    )

    create unique_index(:transactions, [:plaid_transaction_id],
             name: "transactions_unique_plaid_id_index",
             prefix: "core"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id],
        name: "transactions_unique_plaid_id_index",
        prefix: "core"
      )
    )

    create unique_index(:transactions, [:plaid_transaction_id, :date],
             name: "transactions_unique_plaid_transaction_id_index",
             prefix: "core"
           )

    drop_if_exists(
      index(:transactions, [:account_id, :personal_finance_category],
        name: "transactions_account_id_category_index",
        prefix: "core"
      )
    )

    drop_if_exists(
      index(:transactions, [:account_id, :personal_finance_category],
        name: "transactions_outflow_by_account_category_index",
        prefix: "core"
      )
    )
  end
end
