defmodule FinanceSmith.Repo.Migrations.AddTransactionIndexesAndIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Identity change: [:plaid_transaction_id, :date] → [:plaid_transaction_id]

  Plaid can change a transaction's `date` between the "authorized" and "posted"
  states, so the old compound identity allowed duplicate `plaid_transaction_id`
  rows. The new single-column identity collapses those to one canonical row.

  Before creating the new unique index we delete all-but-one row per
  `plaid_transaction_id` (keeping the newest by `inserted_at`) to ensure the
  migration succeeds on environments that already processed historical syncs.
  """

  use Ecto.Migration

  def up do
    create index(:transactions, [:account_id, :personal_finance_category],
             name: "transactions_outflow_by_account_category_index",
             where: "amount > 0",
             prefix: "core"
           )

    create index(:transactions, [:account_id, :personal_finance_category],
             name: "transactions_account_id_category_index",
             prefix: "core"
           )

    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id, :date],
        name: "transactions_unique_plaid_transaction_id_index",
        prefix: "core"
      )
    )

    # Remove duplicate plaid_transaction_id rows before tightening the unique
    # index. For each group of duplicates we keep the row with the latest
    # inserted_at; older duplicates are deleted inside the same transaction.
    execute("""
    DELETE FROM core.transactions
    WHERE id IN (
      SELECT id
      FROM (
        SELECT id,
               ROW_NUMBER() OVER (
                 PARTITION BY plaid_transaction_id
                 ORDER BY inserted_at DESC
               ) AS rn
        FROM core.transactions
      ) ranked
      WHERE rn > 1
    )
    """)

    create unique_index(:transactions, [:plaid_transaction_id],
             name: "transactions_unique_plaid_id_index",
             prefix: "core"
           )
  end

  def down do
    # NOTE: The deduplication performed in up/0 is not reversible. Rolling back
    # restores the old compound index but cannot recover the deleted duplicate rows.
    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id],
        name: "transactions_unique_plaid_id_index",
        prefix: "core"
      )
    )

    create unique_index(:transactions, [:plaid_transaction_id, :date],
             name: "transactions_unique_plaid_transaction_id_index",
             prefix: "core"
           )

    drop_if_exists(
      index(:transactions, [:account_id, :personal_finance_category],
        name: "transactions_account_id_category_index",
        prefix: "core"
      )
    )

    drop_if_exists(
      index(:transactions, [:account_id, :personal_finance_category],
        name: "transactions_outflow_by_account_category_index",
        prefix: "core"
      )
    )
  end
end
