defmodule FinanceSmith.Repo.Migrations.AddAuthLockoutFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:failed_auth_attempts, :bigint, null: false, default: 0)
      add(:locked_until, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:users) do
      remove(:locked_until)
      remove(:failed_auth_attempts)
    end
  end
end
