defmodule FinanceSmith.Repo.Migrations.AddCategoryTaxonomy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions, prefix: "core") do
      add(:meta_category_id, :uuid)
    end

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:meta_categories, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:transactions, prefix: "core") do
      modify(
        :meta_category_id,
        references(:meta_categories,
          column: :id,
          name: "transactions_meta_category_id_fkey",
          type: :uuid,
          on_delete: :nilify_all
        )
      )
    end

    create index(:transactions, [:meta_category_id], prefix: "core")

    alter table(:meta_categories, prefix: "core") do
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :household_id,
        references(:households,
          column: :id,
          name: "meta_categories_household_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:meta_categories, [:household_id, :name],
             name: "meta_categories_unique_name_per_household_index",
             prefix: "core"
           )

    create index(:meta_categories, [:household_id], prefix: "core")

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:category_mappings, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:source_category_token, :text, null: false)
      add(:unreviewed, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :household_id,
        references(:households,
          column: :id,
          name: "category_mappings_household_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :meta_category_id,
        references(:meta_categories,
          column: :id,
          name: "category_mappings_meta_category_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:category_mappings, [:household_id, :provider, :source_category_token],
             name: "category_mappings_unique_mapping_per_household_index",
             prefix: "core"
           )

    create index(:category_mappings, [:household_id], prefix: "core")

    create index(:category_mappings, [:meta_category_id], prefix: "core")
  end

  def down do
    drop_if_exists(index(:category_mappings, [:meta_category_id], prefix: "core"))

    drop_if_exists(index(:category_mappings, [:household_id], prefix: "core"))

    drop(constraint(:category_mappings, "category_mappings_household_id_fkey", prefix: "core"))

    drop(
      constraint(:category_mappings, "category_mappings_meta_category_id_fkey", prefix: "core")
    )

    drop_if_exists(
      unique_index(:category_mappings, [:household_id, :provider, :source_category_token],
        name: "category_mappings_unique_mapping_per_household_index",
        prefix: "core"
      )
    )

    drop(table(:category_mappings, prefix: "core"))

    drop_if_exists(index(:meta_categories, [:household_id], prefix: "core"))

    drop(constraint(:meta_categories, "meta_categories_household_id_fkey", prefix: "core"))

    drop_if_exists(
      unique_index(:meta_categories, [:household_id, :name],
        name: "meta_categories_unique_name_per_household_index",
        prefix: "core"
      )
    )

    alter table(:meta_categories, prefix: "core") do
      remove(:household_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
    end

    drop_if_exists(index(:transactions, [:meta_category_id], prefix: "core"))

    drop(constraint(:transactions, "transactions_meta_category_id_fkey", prefix: "core"))

    alter table(:transactions, prefix: "core") do
      modify(:meta_category_id, :uuid)
    end

    drop(table(:meta_categories, prefix: "core"))

    alter table(:transactions, prefix: "core") do
      remove(:meta_category_id)
    end
  end
end
