defmodule FinanceSmith.Repo.Migrations.AddBudgetTargets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:budget_targets, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:period_type, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :household_id,
        references(:households,
          column: :id,
          name: "budget_targets_household_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :meta_category_id,
        references(:meta_categories,
          column: :id,
          name: "budget_targets_meta_category_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:budget_targets, [:meta_category_id, :period_type],
             name: "budget_targets_unique_period_per_meta_category_index",
             prefix: "core"
           )

    create index(:budget_targets, [:household_id], prefix: "core")

    create index(:budget_targets, [:meta_category_id], prefix: "core")
  end

  def down do
    drop_if_exists(index(:budget_targets, [:meta_category_id], prefix: "core"))

    drop_if_exists(index(:budget_targets, [:household_id], prefix: "core"))

    drop(constraint(:budget_targets, "budget_targets_household_id_fkey", prefix: "core"))

    drop(constraint(:budget_targets, "budget_targets_meta_category_id_fkey", prefix: "core"))

    drop_if_exists(
      unique_index(:budget_targets, [:meta_category_id, :period_type],
        name: "budget_targets_unique_period_per_meta_category_index",
        prefix: "core"
      )
    )

    drop(table(:budget_targets, prefix: "core"))
  end
end
