defmodule FinanceSmith.Repo.Migrations.AddHybridBalanceFetch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plaid_items, prefix: "core") do
      add(:last_balance_synced_at, :utc_datetime_usec)
    end

    alter table(:accounts, prefix: "core") do
      add(:available_balance, :bigint)
    end
  end

  def down do
    alter table(:accounts, prefix: "core") do
      remove(:available_balance)
    end

    alter table(:plaid_items, prefix: "core") do
      remove(:last_balance_synced_at)
    end
  end
end
