defmodule FinanceSmith.Repo.Migrations.AddBudgetTargetWindow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:transactions, [:meta_category_id, :date],
             name: "transactions_meta_category_id_date_index",
             prefix: "core"
           )
  end

  def down do
    drop_if_exists(
      index(:transactions, [:meta_category_id, :date],
        name: "transactions_meta_category_id_date_index",
        prefix: "core"
      )
    )
  end
end
