defmodule FinanceSmith.Repo.Migrations.AddPendingTransactionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions, prefix: "core") do
      add(:pending_transaction_id, :text)
    end

    create index(:transactions, [:pending_transaction_id],
             name: "transactions_pending_transaction_id_index",
             where: "pending_transaction_id IS NOT NULL",
             prefix: "core"
           )
  end

  def down do
    drop_if_exists(
      index(:transactions, [:pending_transaction_id],
        name: "transactions_pending_transaction_id_index",
        prefix: "core"
      )
    )

    alter table(:transactions, prefix: "core") do
      remove(:pending_transaction_id)
    end
  end
end
