defmodule FinanceSmith.Repo.Migrations.AddMfaToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mfa_enabled boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS encrypted_mfa_secret bytea,
    ADD COLUMN IF NOT EXISTS encrypted_recovery_codes bytea
    """
  end

  def down do
    alter table(:users) do
      remove(:encrypted_recovery_codes, :binary)
      remove(:encrypted_mfa_secret, :binary)
      remove(:mfa_enabled, :boolean)
    end
  end
end
