defmodule FinanceSmith.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:email, :text, null: false)
      add(:password_hash, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:household_id, :uuid, null: false)
    end

    create table(:transactions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:plaid_transaction_id, :text, null: false)
      add(:amount, :bigint)
      add(:date, :date, null: false)
      add(:merchant_name, :text)
      add(:category, {:array, :text})
      add(:is_pending, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:account_id, :uuid, null: false)
    end

    create index(:transactions, [:account_id],
             name: "transactions_pending_by_account_index",
             where: "is_pending = true"
           )

    create index(:transactions, [:account_id, :date], name: "transactions_account_id_date_index")

    create table(:plaid_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:plaid_item_id, :text, null: false)
      add(:institution_name, :text)
      add(:next_cursor, :text)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "plaid_items_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(:encrypted_access_token, :binary, null: false)
    end

    create index(:plaid_items, [:user_id])

    create unique_index(:plaid_items, [:plaid_item_id],
             name: "plaid_items_unique_plaid_item_id_index"
           )

    create table(:households, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:users) do
      modify(
        :household_id,
        references(:households,
          column: :id,
          name: "users_household_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create index(:users, [:household_id])

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:households) do
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:transactions) do
      modify(
        :account_id,
        references(:accounts,
          column: :id,
          name: "transactions_account_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create index(:transactions, [:account_id])

    create unique_index(:transactions, [:plaid_transaction_id, :date],
             name: "transactions_unique_plaid_transaction_id_index"
           )

    alter table(:accounts) do
      add(:plaid_account_id, :text, null: false)
      add(:name, :text)
      add(:mask, :text)
      add(:type, :text)
      add(:subtype, :text)
      add(:current_balance, :bigint)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :plaid_item_id,
        references(:plaid_items,
          column: :id,
          name: "accounts_plaid_item_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :duplicate_of_id,
        references(:accounts,
          column: :id,
          name: "accounts_duplicate_of_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :nilify_all
        )
      )
    end

    create index(:accounts, [:plaid_item_id, :status],
             name: "accounts_plaid_item_id_status_index"
           )

    create index(:accounts, [:plaid_item_id])

    create index(:accounts, [:duplicate_of_id])

    create unique_index(:accounts, [:plaid_account_id],
             name: "accounts_unique_plaid_account_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:accounts, [:plaid_account_id], name: "accounts_unique_plaid_account_id_index")
    )

    drop_if_exists(index(:accounts, [:duplicate_of_id]))

    drop_if_exists(index(:accounts, [:plaid_item_id]))

    drop(constraint(:accounts, "accounts_plaid_item_id_fkey"))

    drop(constraint(:accounts, "accounts_duplicate_of_id_fkey"))

    drop_if_exists(
      index(:accounts, [:plaid_item_id, :status], name: "accounts_plaid_item_id_status_index")
    )

    alter table(:accounts) do
      remove(:duplicate_of_id)
      remove(:plaid_item_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:current_balance)
      remove(:subtype)
      remove(:type)
      remove(:mask)
      remove(:name)
      remove(:plaid_account_id)
    end

    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id, :date],
        name: "transactions_unique_plaid_transaction_id_index"
      )
    )

    drop_if_exists(index(:transactions, [:account_id]))

    drop(constraint(:transactions, "transactions_account_id_fkey"))

    alter table(:transactions) do
      modify(:account_id, :uuid)
    end

    drop(table(:accounts))

    alter table(:households) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
    end

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop_if_exists(index(:users, [:household_id]))

    drop(constraint(:users, "users_household_id_fkey"))

    alter table(:users) do
      modify(:household_id, :uuid)
    end

    drop(table(:households))

    drop_if_exists(
      unique_index(:plaid_items, [:plaid_item_id], name: "plaid_items_unique_plaid_item_id_index")
    )

    drop_if_exists(index(:plaid_items, [:user_id]))

    drop(constraint(:plaid_items, "plaid_items_user_id_fkey"))

    drop(table(:plaid_items))

    drop_if_exists(
      index(:transactions, [:account_id, :date], name: "transactions_account_id_date_index")
    )

    drop_if_exists(
      index(:transactions, [:account_id], name: "transactions_pending_by_account_index")
    )

    drop(table(:transactions))

    drop(table(:users))
  end
end
