defmodule FinanceSmith.Repo.Migrations.AddMetaCategoriesAndMappings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:meta_categories, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :household_id,
        references(:households,
          column: :id,
          name: "meta_categories_household_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "meta_categories_created_by_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :nilify_all
        )
      )
    end

    create unique_index(:meta_categories, [:household_id, :name],
             name: "meta_categories_unique_household_name_index",
             prefix: "core"
           )

    create index(:meta_categories, [:household_id], prefix: "core")

    create index(:meta_categories, [:created_by_id], prefix: "core")

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:category_mappings, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:plaid_category, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :household_id,
        references(:households,
          column: :id,
          name: "category_mappings_household_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :meta_category_id,
        references(:meta_categories,
          column: :id,
          name: "category_mappings_meta_category_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "category_mappings_created_by_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :nilify_all
        )
      )
    end

    create unique_index(:category_mappings, [:household_id, :plaid_category],
             name: "category_mappings_unique_household_plaid_category_index",
             prefix: "core"
           )

    create index(:category_mappings, [:household_id], prefix: "core")

    create index(:category_mappings, [:meta_category_id], prefix: "core")

    create index(:category_mappings, [:created_by_id], prefix: "core")
  end

  def down do
    drop_if_exists(index(:category_mappings, [:created_by_id], prefix: "core"))

    drop_if_exists(index(:category_mappings, [:meta_category_id], prefix: "core"))

    drop_if_exists(index(:category_mappings, [:household_id], prefix: "core"))

    drop(constraint(:category_mappings, "category_mappings_household_id_fkey", prefix: "core"))

    drop(
      constraint(:category_mappings, "category_mappings_meta_category_id_fkey", prefix: "core")
    )

    drop(constraint(:category_mappings, "category_mappings_created_by_id_fkey", prefix: "core"))

    drop_if_exists(
      unique_index(:category_mappings, [:household_id, :plaid_category],
        name: "category_mappings_unique_household_plaid_category_index",
        prefix: "core"
      )
    )

    drop(table(:category_mappings, prefix: "core"))

    drop_if_exists(index(:meta_categories, [:created_by_id], prefix: "core"))

    drop_if_exists(index(:meta_categories, [:household_id], prefix: "core"))

    drop(constraint(:meta_categories, "meta_categories_household_id_fkey", prefix: "core"))

    drop(constraint(:meta_categories, "meta_categories_created_by_id_fkey", prefix: "core"))

    drop_if_exists(
      unique_index(:meta_categories, [:household_id, :name],
        name: "meta_categories_unique_household_name_index",
        prefix: "core"
      )
    )

    drop(table(:meta_categories, prefix: "core"))
  end
end
