defmodule FinanceSmith.Repo.Migrations.InitCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:users, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:email, :text, null: false)
      add(:password_hash, :text, null: false)
      add(:mfa_enabled, :boolean, null: false, default: false)
      add(:failed_auth_attempts, :bigint, null: false, default: 0)
      add(:locked_until, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:household_id, :uuid, null: false)
      add(:encrypted_mfa_secret, :binary)
      add(:encrypted_recovery_codes, :binary)
    end

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:transactions, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:plaid_transaction_id, :text, null: false)
      add(:amount, :bigint)
      add(:date, :date, null: false)
      add(:merchant_name, :text)
      add(:personal_finance_category, :text)
      add(:website, :text)
      add(:is_pending, :boolean, null: false, default: false)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:account_id, :uuid, null: false)
    end

    create index(:transactions, [:date, :amount],
             name: "transactions_date_amount_index",
             prefix: "core"
           )

    create index(:transactions, [:metadata],
             name: "transactions_metadata_gin_index",
             using: "GIN",
             prefix: "core"
           )

    create index(:transactions, [:account_id],
             name: "transactions_pending_by_account_index",
             where: "is_pending = true",
             prefix: "core"
           )

    create index(:transactions, [:account_id, :date],
             name: "transactions_account_id_date_index",
             prefix: "core"
           )

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:plaid_items, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:plaid_item_id, :text, null: false)
      add(:institution_name, :text)
      add(:last_synced_at, :utc_datetime_usec)
      add(:next_cursor, :text)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "plaid_items_user_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(:encrypted_access_token, :binary, null: false)
    end

    create index(:plaid_items, [:user_id], prefix: "core")

    create unique_index(:plaid_items, [:plaid_item_id],
             name: "plaid_items_unique_plaid_item_id_index",
             prefix: "core"
           )

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:households, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:users, prefix: "core") do
      modify(
        :household_id,
        references(:households,
          column: :id,
          name: "users_household_id_fkey",
          type: :uuid,
          on_delete: :restrict
        )
      )
    end

    create index(:users, [:household_id], prefix: "core")

    create unique_index(:users, [:email], name: "users_unique_email_index", prefix: "core")

    alter table(:households, prefix: "core") do
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    execute("CREATE SCHEMA IF NOT EXISTS core")

    create table(:accounts, primary_key: false, prefix: "core") do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:transactions, prefix: "core") do
      modify(
        :account_id,
        references(:accounts,
          column: :id,
          name: "transactions_account_id_fkey",
          type: :uuid,
          on_delete: :delete_all
        )
      )
    end

    create index(:transactions, [:account_id], prefix: "core")

    create unique_index(:transactions, [:plaid_transaction_id, :date],
             name: "transactions_unique_plaid_transaction_id_index",
             prefix: "core"
           )

    alter table(:accounts, prefix: "core") do
      add(:plaid_account_id, :text, null: false)
      add(:name, :text)
      add(:mask, :text)
      add(:type, :text)
      add(:subtype, :text)
      add(:current_balance, :bigint)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :plaid_item_id,
        references(:plaid_items,
          column: :id,
          name: "accounts_plaid_item_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :delete_all
        ), null: false)

      add(
        :duplicate_of_id,
        references(:accounts,
          column: :id,
          name: "accounts_duplicate_of_id_fkey",
          type: :uuid,
          prefix: "core",
          on_delete: :nilify_all
        )
      )
    end

    create index(:accounts, [:plaid_item_id, :status],
             name: "accounts_plaid_item_id_status_index",
             prefix: "core"
           )

    create index(:accounts, [:plaid_item_id], prefix: "core")

    create index(:accounts, [:duplicate_of_id], prefix: "core")

    create unique_index(:accounts, [:plaid_account_id],
             name: "accounts_unique_plaid_account_id_index",
             prefix: "core"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:accounts, [:plaid_account_id],
        name: "accounts_unique_plaid_account_id_index",
        prefix: "core"
      )
    )

    drop_if_exists(index(:accounts, [:duplicate_of_id], prefix: "core"))

    drop_if_exists(index(:accounts, [:plaid_item_id], prefix: "core"))

    drop(constraint(:accounts, "accounts_plaid_item_id_fkey", prefix: "core"))

    drop(constraint(:accounts, "accounts_duplicate_of_id_fkey", prefix: "core"))

    drop_if_exists(
      index(:accounts, [:plaid_item_id, :status],
        name: "accounts_plaid_item_id_status_index",
        prefix: "core"
      )
    )

    alter table(:accounts, prefix: "core") do
      remove(:duplicate_of_id)
      remove(:plaid_item_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:status)
      remove(:current_balance)
      remove(:subtype)
      remove(:type)
      remove(:mask)
      remove(:name)
      remove(:plaid_account_id)
    end

    drop_if_exists(
      unique_index(:transactions, [:plaid_transaction_id, :date],
        name: "transactions_unique_plaid_transaction_id_index",
        prefix: "core"
      )
    )

    drop_if_exists(index(:transactions, [:account_id], prefix: "core"))

    drop(constraint(:transactions, "transactions_account_id_fkey", prefix: "core"))

    alter table(:transactions, prefix: "core") do
      modify(:account_id, :uuid)
    end

    drop(table(:accounts, prefix: "core"))

    alter table(:households, prefix: "core") do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
    end

    drop_if_exists(
      unique_index(:users, [:email], name: "users_unique_email_index", prefix: "core")
    )

    drop_if_exists(index(:users, [:household_id], prefix: "core"))

    drop(constraint(:users, "users_household_id_fkey", prefix: "core"))

    alter table(:users, prefix: "core") do
      modify(:household_id, :uuid)
    end

    drop(table(:households, prefix: "core"))

    drop_if_exists(
      unique_index(:plaid_items, [:plaid_item_id],
        name: "plaid_items_unique_plaid_item_id_index",
        prefix: "core"
      )
    )

    drop_if_exists(index(:plaid_items, [:user_id], prefix: "core"))

    drop(constraint(:plaid_items, "plaid_items_user_id_fkey", prefix: "core"))

    drop(table(:plaid_items, prefix: "core"))

    drop_if_exists(
      index(:transactions, [:account_id, :date],
        name: "transactions_account_id_date_index",
        prefix: "core"
      )
    )

    drop_if_exists(
      index(:transactions, [:account_id],
        name: "transactions_pending_by_account_index",
        prefix: "core"
      )
    )

    drop_if_exists(
      index(:transactions, [:metadata], name: "transactions_metadata_gin_index", prefix: "core")
    )

    drop_if_exists(
      index(:transactions, [:date, :amount],
        name: "transactions_date_amount_index",
        prefix: "core"
      )
    )

    drop(table(:transactions, prefix: "core"))

    drop(table(:users, prefix: "core"))
  end
end
