defmodule FinanceSmith.Repo.Migrations.AddLastSyncedAtToPlaidItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plaid_items) do
      add(:last_synced_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:plaid_items) do
      remove(:last_synced_at)
    end
  end
end
